name:  Continuous Deployment

on:
  push:
    branches: [master, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: Azure/docker-login@v1
        with:
          login-server: learnqsharpapi.azurecr.io
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - run: |
          docker build . -t learnqsharpapi.azurecr.io/learnqsharpapi:${{ github.sha }}
          docker push learnqsharpapi.azurecr.io/learnqsharpapi:${{ github.sha }}

      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        if: github.ref == 'refs/heads/master'
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: learn-qsharp-production
          resource-group: learnQSharp

      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        if: github.ref == 'refs/heads/develop'
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: learn-qsharp-staging
          resource-group: learnQSharp

      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: learnqsharpapi.azurecr.io
          container-registry-username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          secret-name: demo-k8s-secret

      - uses: Azure/k8s-deploy@v1
        if: github.ref == 'refs/heads/master'
        with:
          manifests: |
            deployment-production.yml
          images: |
            learnqsharpapi.azurecr.io/learnqsharpapi:${{ github.sha }}
          namespace: learn-qsharp-api
          imagepullsecrets: |
            demo-k8s-secret

      - uses: Azure/k8s-deploy@v1
        if: github.ref == 'refs/heads/develop'
        with:
          manifests: |
            deployment-staging.yml
          images: |
            learnqsharpapi.azurecr.io/learnqsharpapi:${{ github.sha }}
          namespace: learn-qsharp-api
          imagepullsecrets: |
            demo-k8s-secret
